services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: sales-ai-postgres
    environment:
      POSTGRES_DB: sales_ai_platform
      POSTGRES_USER: sales_ai_user
      POSTGRES_PASSWORD: sales_ai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra-migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sales_ai_user -d sales_ai_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sales-ai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: sales_ai_user
      RABBITMQ_DEFAULT_PASS: sales_ai_password
      RABBITMQ_DEFAULT_VHOST: sales_ai_vhost
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache
  redis:
    image: redis:7-alpine
    container_name: sales-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  default:
    name: sales-ai-network
